### ISSUE TITLE
Driver does not load on Android 11 (VNDK10)

### ISSUE THREAD

**Issue by lfom** [ilhan-athn7/freedreno_turnip-CI#1]
Hello, there!

I was trying to install turnip on my device running a custom A11 ROM that uses VNDK10, but it does not load. logcat shows:
```
$ adb wait-for-device && adb logcat *:W | grep -i vulkan
01-10 01:04:48.062  5294  5294 E vndksupport: Could not load vulkan.adreno.so from sphal namespace: dlopen failed: cannot locate symbol "atrace_get_enabled_tags" referenced by "/vendor/lib64/hw/vulkan.adreno.so"....
```
But it seems that all dependencies are met (the trace symbol is a part of libcutil from what I have read online):
```
# ldd /vendor/lib64/hw/vulkan.adreno.so                                                                
	linux-vdso.so.1 => [vdso] (0x72a04b1000)
	libcutils.so => /system/lib64/libcutils.so (0x729ea2b000)
	libhardware.so => /system/lib64/libhardware.so (0x729e9fa000)
	liblog.so => /system/lib64/liblog.so (0x729e95d000)
	libsync.so => /system/lib64/libsync.so (0x729ea5b000)
	libm.so => /apex/com.android.runtime/lib64/bionic/libm.so (0x729eb80000)
	libz.so => /system/lib64/libz.so (0x729eb53000)
	libdl.so => /apex/com.android.runtime/lib64/bionic/libdl.so (0x729ec08000)
	libc.so => /apex/com.android.runtime/lib64/bionic/libc.so (0x729e84e000)
	libbase.so => /system/lib64/libbase.so (0x729ebc2000)
	libc++.so => /system/lib64/libc++.so (0x729ea81000)
	libvndksupport.so => /system/lib64/libvndksupport.so (0x729e9b9000)
	libdl_android.so => /apex/com.android.runtime/lib64/bionic/libdl_android.so (0x729ec41000)
```
Checking the builder script, it seems that it uses `-Dplatform-sdk-version=31` while the documentation suggests 26:

https://docs.mesa3d.org/android.html#building-using-the-android-ndk

Any special reason to use 31? 26 (or at least 29) will not work with your device? Could you please try a build with a lower SDK? Thanks.

Regards

**Comment by ilhan-athn7** [comment]
Hi, thanks you for letting me know about this,
Can you test below file and confirm that it is work?

[turnip.zip](https://github.com/ilhan-athn7/freedreno_turnip-CI/files/10385478/turnip.zip)

**Comment by ilhan-athn7** [comment]
Sorry, this seems to be beyond me,

In that case, you can create a new [issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues) .

**Comment by ilhan-athn7** [comment]
Hi, as you open a new issue, i realized that a610 is not enabled in the source 😅
So, try this new one from here;
https://github.com/ilhan-athn7/freedreno_turnip-CI/actions/runs/3899616879

**Comment by lfom** [comment]
New MR to add A610 support, hopefully it will get merged:

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/20991/diffs?commit_id=71c488ee7c360998cb943207539f45263f2f2fa3

**Comment by ilhan-athn7** [comment]
https://github.com/ilhan-athn7/freedreno_turnip-CI/actions/runs/4842295349
Good luck 👍

**Comment by lfom** [comment]
@ilhan-athn7 Hey, thank you for the new build! I saw that you fetched the source code for the MR then built it again. The error changed, now it says:

```
04-30 11:12:23.640  8785  8807 E vndksupport: Could not load vulkan.adreno.so from sphal namespace: dlopen failed: library "vulkan.adreno.so" not found.
```

But the new file is there... Maybe it also needs the 32-bit library? I tried using Vulkan Caps Viewer and 3D Mark, both are listed as arm64-v8a. I tried renaming it to vulkan.trinket.so, no deal.

**Comment by ilhan-athn7** [comment]
So it is `vulkan.trinket.so`, we must change shared object name to it.(The patchelf step of build process)

**Comment by ilhan-athn7** [comment]
https://github.com/ilhan-athn7/freedreno_turnip-CI/actions/runs/4844909402

**Comment by lfom** [comment]
> So it is `vulkan.trinket.so`, we must change shared object name to it.(The patchelf step of build process)

Actually it works with **vulkan.adreno.so too**... I messed up earlier, sorry: I am using Magisk Delta and it changed the way Magisk Hide works so I had to "unhide" the apps so it could load the new libraries. Then they could find the file, but got the same error again... :disappointed: 

```
04-30 16:55:17.931 13562 13581 E vndksupport: Could not load vulkan.adreno.so from sphal namespace: dlopen failed: cannot locate symbol "atrace_get_enabled_tags" referenced by "/vendor/lib64/hw/vulkan.adreno.so"....
04-30 16:55:17.933 13562 13581 E vndksupport: Could not load vulkan.trinket.so from sphal namespace: dlopen failed: cannot locate symbol "atrace_get_enabled_tags" referenced by "/vendor/lib64/hw/vulkan.trinket.so"....
``` 
`ldd` shows no errors still...

**Comment by ilhan-athn7** [comment]
Maybe we can hack this line;
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/include/android_stub/cutils/trace.h#L150

It is wrong but might help us.

**Comment by lfom** [comment]
Hey, it looks like it worked! I could not find what exactly you changed, but there was no error anymore, and both Vulkan Caps Viewer and 3D Mark worked!

![Screenshot_20230501-182427_Vulkan_Caps_Viewer](https://user-images.githubusercontent.com/15659999/235535458-1179ebfc-e644-4c27-8090-b222a3db309c.png)


The performance actually decreased tho, I was expecting it to increase. This was already the branch meant to support A610, with a patch to avoid the error message, right? So probably there is nothing else that can be done to improve performance, I presume?

Thanks again!

**Comment by ilhan-athn7** [comment]
> Maybe we can hack this line; https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/include/android_stub/cutils/trace.h#L150

So i did it [here](https://gitlab.freedesktop.org/MrMiy4mo/mesa/-/commit/c5a63a1639f44e3175b638ca6ea6b0526d9f8d7e?action=show&controller=projects%2Fcommit&id=c5a63a1639f44e3175b638ca6ea6b0526d9f8d7e&namespace_id=MrMiy4mo&project_id=mesa) 
I don't actually know how it should be fixed.

**Comment by ilhan-athn7** [comment]
@nesper8 @romanovj

You guys seems been trying get turnip work with adreno 610
Fyi, i already built it some time ago;
https://github.com/ilhan-athn7/freedreno_turnip-CI/actions/runs/4848372913

**Comment by lfom** [comment]
@ilhan-athn7 I have seen some activity in the MESA repository, I think a dev is adding some optimizations for the 610. Hopefully it will improve performance, but I don't know if it is stable already.
