### ISSUE TITLE
uploading turnip releases to artifacts

### ISSUE THREAD

**Issue by nesper8** [ilhan-athn7/freedreno_turnip-CI#2]
Hi this is my first time dabbling into GitHub actions so how can I leverage workflows to upload the driver artifacts to GH Actions?

**Comment by ilhan-athn7** [comment]
![IMG-20230607-WA0002](https://github.com/ilhan-athn7/freedreno_turnip-CI/assets/80551220/c5255159-d31e-4c9a-9b77-a1efa014b9c9)
This part is responsible for uploading files to releases.
Good luck 🫡
