### ISSUE TITLE
Adreno 508?

### ISSUE THREAD

**Issue by Yisus7u7** [ilhan-athn7/freedreno_turnip-CI#4]
Is this compatible with Adreno 508? In my case it didn't work.

https://github.com/termux-user-repository/tur/issues/560

![Screenshot_20230902-233358_KernelSU](https://github.com/ilhan-athn7/freedreno_turnip-CI/assets/64093255/60b241d8-58ed-4e83-a043-961273ab7e37)
![Screenshot_20230902-233533_Termux](https://github.com/ilhan-athn7/freedreno_turnip-CI/assets/64093255/d462fdf7-3f87-42f4-8b82-5ca861148b75)
![Screenshot_20230902-233051_Termux](https://github.com/ilhan-athn7/freedreno_turnip-CI/assets/64093255/2a11a695-94e7-4d4d-905f-6f7a73e96cad)

**Comment by ilhan-athn7** [comment]
Hi, unfortunately adreno 5xx series are not supported.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5491#note_1102667
